apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: panna-app
    tier: frontend
  name: panna

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: panna-app
  name: panna-app-deployment
  namespace: panna
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: panna-app-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: panna-app
        release: r11082019
    spec:
      containers:
          image: gcr.io/bjp-saral/github.com/jarvisconsulting/panna
          imagePullPolicy: IfNotPresent
          name: panna-deployment
          resources:
            limits:
              cpu: 1000m
              memory: 1042Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: panna-app
  name: panna-service
  namespace: panna
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: panna-app
  sessionAffinity: None
  type: LoadBalancer
